version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1642
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: waitress-serve --port=8000 MGA_ZADANIE.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: